name: Test Whitespace and line endings

on: [pull_request]

permissions:
  contents: read

jobs:
  eclint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - run: npm i -g eclint
      - run: eclint check
